### ISSUE TITLE
Nuget pkg install problem

### ISSUE THREAD

**Issue by meghma** [dapplo/Dapplo.Confluence#3]
Even with latest update 0.1.29 as of 6/17 , the package does not install due to underlying problem
in Dapplo.HttpExtensions , which seem to have a conflicting version for System.Net.Http
I am using Nuget 2.8.50926.663 in VS 2013

**Comment by Lakritzator** [comment]
I guess the error is still:
`The error message is Attempting to resolve dependency
Dapplo.Confluence has already a dependency defined for Dapplo.HttpExtensions
Dapplo.HttpExtensions already has a dependency defined for System.Net.Http`

And your project is set to .NET 4.5.1?

Dapplo.Confluence 0.1.28 somehow was still targeted to 4.5.2, so that clearly didn't work.
But Dapplo.Confluence 0.1.29 is really targeted for 4.5, so at least that should be okay.

I don't see any issues with the Dapplo.HttpExtensions target, maybe the 
`<frameworkAssembly assemblyName="System.Net.Http" targetFramework="net40" />`
Gives problems, but I don't have any issues in my visual studio...

So either it's that, or a problem with Nuget 2.8 (which is old, but for VS 2013 there are no updates) or the package is somehow causing issues in Visual Studio 2013 (I use 2015).

I could try to remove the frameworkAssembly in a pre-release, so we can test this, maybe it helps.
Leaving it out, forces you to have to add this manually...

Or maybe you really already added a System.Net.Http reference yourself, manually, for a different version?

**Comment by Lakritzator** [comment]
If possible, just test with a clean solution, with a console project which is targeting 4.5.1.
So I know if this might be due to you adding it to a corrupt project...

**Comment by Lakritzator** [comment]
What is the status here? Did it work, can I close this?

**Comment by meghma** [comment]
Yo can close as this wouldn't work as Atlassian hasn't exposed the calendar object as rest apis


Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by Lakritzator** [comment]
To motivate Atlassian to build their API, please comment your use-case here: https://jira.atlassian.com/browse/TEAMCAL-269
Their team is requesting this...
