### ISSUE TITLE
Problem with installing Nuget pacakge on Viusla Studio 2015 c# Windows Form template

### ISSUE THREAD

**Issue by LukaszZimny** [dapplo/Dapplo.Confluence#37]
Hello,
When I try to install package I receive error. Could help to solve it. 

> Severity	Code	Description	Project	File	Line	Suppression State
> Error		Could not install package 'Dapplo.Confluence 0.8.20'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by Lakritzator** [comment]
If you read the error in details it says what is wrong:
**Your** project is targeting .NET Framework 4.5 and the Dapplo.Confluence package doesn't support this.

You can see the support versions on NuGet: https://www.nuget.org/packages/Dapplo.Confluence
That is the answer to your problem.


Now WHY I don't support 4.5, that is another discussion. But in general 4.5 doesn't offer some features I need and my view on the framework versions is that the least version should be 4.6.1 but due to netstandard incompatibilities I advice to use 4.7.1.

I noticed that I taken my advice to strict, and upgraded most of my packages to 4.7.1 which is not needed for most cases. I will change my targets right away, to support 4.6.1 but will and mostly can not go lower.

I'm curious why you are still targeting 4.5, as you would miss out on many fixes and can't use a lot of nuget packages!

**Comment by LukaszZimny** [comment]
Hello,
I have all version installed of .NET including 4.7.2 so I have no idea why VS2015 wanted to install it as .NET 4.5 (some limitation maybe). I will try to install it on VS2019 at home and I hope it will go without any problems.

**Comment by Lakritzator** [comment]
I guess you forgot to change the target somewhere when creating the project, but you can always change it afterwards.

VS2015 is a limitation too... I hope you are not stuck with that version, with dotnet core 3.0 coming out soon you can't use the good stuff.

I've updated the Dapplo.Confluence package, you can also target .NET Framework 4.6.1 if you want, but if possible do use 4.7.1!!

Closing this issue, as I assume it will be solved as soon as you target 4.6.1 or later. Other questions should be asked in other issues.
